/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedUsuariosPerfilRouteImport } from './routes/_authed/usuarios/perfil'
import { Route as AuthedUsuariosAdminRouteImport } from './routes/_authed/usuarios/admin'
import { Route as AuthedParametrosProyectosRouteImport } from './routes/_authed/parametros/proyectos'
import { Route as AuthedParametrosProveedoresRouteImport } from './routes/_authed/parametros/proveedores'
import { Route as AuthedParametrosPartidasRouteImport } from './routes/_authed/parametros/partidas'
import { Route as AuthedParametrosMaterialesRouteImport } from './routes/_authed/parametros/materiales'
import { Route as AuthedParametrosCategoriasRouteImport } from './routes/_authed/parametros/categorias'
import { Route as AuthedParametrosRubrosIndexRouteImport } from './routes/_authed/parametros/rubros/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedUsuariosPerfilRoute = AuthedUsuariosPerfilRouteImport.update({
  id: '/usuarios/perfil',
  path: '/usuarios/perfil',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUsuariosAdminRoute = AuthedUsuariosAdminRouteImport.update({
  id: '/usuarios/admin',
  path: '/usuarios/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedParametrosProyectosRoute =
  AuthedParametrosProyectosRouteImport.update({
    id: '/parametros/proyectos',
    path: '/parametros/proyectos',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedParametrosProveedoresRoute =
  AuthedParametrosProveedoresRouteImport.update({
    id: '/parametros/proveedores',
    path: '/parametros/proveedores',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedParametrosPartidasRoute =
  AuthedParametrosPartidasRouteImport.update({
    id: '/parametros/partidas',
    path: '/parametros/partidas',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedParametrosMaterialesRoute =
  AuthedParametrosMaterialesRouteImport.update({
    id: '/parametros/materiales',
    path: '/parametros/materiales',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedParametrosCategoriasRoute =
  AuthedParametrosCategoriasRouteImport.update({
    id: '/parametros/categorias',
    path: '/parametros/categorias',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedParametrosRubrosIndexRoute =
  AuthedParametrosRubrosIndexRouteImport.update({
    id: '/parametros/rubros/',
    path: '/parametros/rubros/',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/parametros/categorias': typeof AuthedParametrosCategoriasRoute
  '/parametros/materiales': typeof AuthedParametrosMaterialesRoute
  '/parametros/partidas': typeof AuthedParametrosPartidasRoute
  '/parametros/proveedores': typeof AuthedParametrosProveedoresRoute
  '/parametros/proyectos': typeof AuthedParametrosProyectosRoute
  '/usuarios/admin': typeof AuthedUsuariosAdminRoute
  '/usuarios/perfil': typeof AuthedUsuariosPerfilRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/parametros/rubros': typeof AuthedParametrosRubrosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/parametros/categorias': typeof AuthedParametrosCategoriasRoute
  '/parametros/materiales': typeof AuthedParametrosMaterialesRoute
  '/parametros/partidas': typeof AuthedParametrosPartidasRoute
  '/parametros/proveedores': typeof AuthedParametrosProveedoresRoute
  '/parametros/proyectos': typeof AuthedParametrosProyectosRoute
  '/usuarios/admin': typeof AuthedUsuariosAdminRoute
  '/usuarios/perfil': typeof AuthedUsuariosPerfilRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/parametros/rubros': typeof AuthedParametrosRubrosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/parametros/categorias': typeof AuthedParametrosCategoriasRoute
  '/_authed/parametros/materiales': typeof AuthedParametrosMaterialesRoute
  '/_authed/parametros/partidas': typeof AuthedParametrosPartidasRoute
  '/_authed/parametros/proveedores': typeof AuthedParametrosProveedoresRoute
  '/_authed/parametros/proyectos': typeof AuthedParametrosProyectosRoute
  '/_authed/usuarios/admin': typeof AuthedUsuariosAdminRoute
  '/_authed/usuarios/perfil': typeof AuthedUsuariosPerfilRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/parametros/rubros/': typeof AuthedParametrosRubrosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/parametros/categorias'
    | '/parametros/materiales'
    | '/parametros/partidas'
    | '/parametros/proveedores'
    | '/parametros/proyectos'
    | '/usuarios/admin'
    | '/usuarios/perfil'
    | '/api/auth/$'
    | '/parametros/rubros'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/parametros/categorias'
    | '/parametros/materiales'
    | '/parametros/partidas'
    | '/parametros/proveedores'
    | '/parametros/proyectos'
    | '/usuarios/admin'
    | '/usuarios/perfil'
    | '/api/auth/$'
    | '/parametros/rubros'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/dashboard'
    | '/_authed/parametros/categorias'
    | '/_authed/parametros/materiales'
    | '/_authed/parametros/partidas'
    | '/_authed/parametros/proveedores'
    | '/_authed/parametros/proyectos'
    | '/_authed/usuarios/admin'
    | '/_authed/usuarios/perfil'
    | '/api/auth/$'
    | '/_authed/parametros/rubros/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/usuarios/perfil': {
      id: '/_authed/usuarios/perfil'
      path: '/usuarios/perfil'
      fullPath: '/usuarios/perfil'
      preLoaderRoute: typeof AuthedUsuariosPerfilRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/usuarios/admin': {
      id: '/_authed/usuarios/admin'
      path: '/usuarios/admin'
      fullPath: '/usuarios/admin'
      preLoaderRoute: typeof AuthedUsuariosAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/parametros/proyectos': {
      id: '/_authed/parametros/proyectos'
      path: '/parametros/proyectos'
      fullPath: '/parametros/proyectos'
      preLoaderRoute: typeof AuthedParametrosProyectosRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/parametros/proveedores': {
      id: '/_authed/parametros/proveedores'
      path: '/parametros/proveedores'
      fullPath: '/parametros/proveedores'
      preLoaderRoute: typeof AuthedParametrosProveedoresRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/parametros/partidas': {
      id: '/_authed/parametros/partidas'
      path: '/parametros/partidas'
      fullPath: '/parametros/partidas'
      preLoaderRoute: typeof AuthedParametrosPartidasRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/parametros/materiales': {
      id: '/_authed/parametros/materiales'
      path: '/parametros/materiales'
      fullPath: '/parametros/materiales'
      preLoaderRoute: typeof AuthedParametrosMaterialesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/parametros/categorias': {
      id: '/_authed/parametros/categorias'
      path: '/parametros/categorias'
      fullPath: '/parametros/categorias'
      preLoaderRoute: typeof AuthedParametrosCategoriasRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/parametros/rubros/': {
      id: '/_authed/parametros/rubros/'
      path: '/parametros/rubros'
      fullPath: '/parametros/rubros'
      preLoaderRoute: typeof AuthedParametrosRubrosIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedParametrosCategoriasRoute: typeof AuthedParametrosCategoriasRoute
  AuthedParametrosMaterialesRoute: typeof AuthedParametrosMaterialesRoute
  AuthedParametrosPartidasRoute: typeof AuthedParametrosPartidasRoute
  AuthedParametrosProveedoresRoute: typeof AuthedParametrosProveedoresRoute
  AuthedParametrosProyectosRoute: typeof AuthedParametrosProyectosRoute
  AuthedUsuariosAdminRoute: typeof AuthedUsuariosAdminRoute
  AuthedUsuariosPerfilRoute: typeof AuthedUsuariosPerfilRoute
  AuthedParametrosRubrosIndexRoute: typeof AuthedParametrosRubrosIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedParametrosCategoriasRoute: AuthedParametrosCategoriasRoute,
  AuthedParametrosMaterialesRoute: AuthedParametrosMaterialesRoute,
  AuthedParametrosPartidasRoute: AuthedParametrosPartidasRoute,
  AuthedParametrosProveedoresRoute: AuthedParametrosProveedoresRoute,
  AuthedParametrosProyectosRoute: AuthedParametrosProyectosRoute,
  AuthedUsuariosAdminRoute: AuthedUsuariosAdminRoute,
  AuthedUsuariosPerfilRoute: AuthedUsuariosPerfilRoute,
  AuthedParametrosRubrosIndexRoute: AuthedParametrosRubrosIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
